version: "3.8"

services:
  frontend:
    build:
      context: .
      target: frontend-server
    ports:
      - "80:80"
    container_name: frontend

  backend:
    build:
      context: .
      target: backend
    ports:
      - "8001:8001"
    privileged: true
    container_name: backend
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
