version: "3.8"

services:
  frontend:
    build:
      context: .
      target: frontend-server
    ports:
      - "80:80"
    volumes:
      - ./frontend/.env:/frontend/.env
    container_name: frontend
    networks:
      - my-network

  backend:
    build:
      context: .
      target: backend
    ports:
      - "8001:8001"
    container_name: backend
    privileged: true
    networks:
      - my-network
    devices:
      - "/dev/gpiomem:/dev/gpiomem"

networks:
  my-network:
    driver: bridge
